# Generated by Django 4.1.3 on 2022-12-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classimage", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Hotel", new_name="Face",),
        migrations.RenameField(
            model_name="face", old_name="hotel_Main_Img", new_name="face_Main_Img",
        ),
    ]
